# -*- coding: utf-8 -*-
"""Resume Parsing with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLyUGN2T63eAIXjrL6URaOUPbYnuXGUn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('ResumeDataSet.csv')

df.head()

df.shape

"""# Exploring Categories"""

df['Category'].value_counts()

plt.figure(figsize=(15,5))
sns.countplot(df['Category'])
plt.xticks(rotation=90)
plt.show()

df['Category'].unique()

counts = df['Category'].value_counts()
labels = df['Category'].unique()
plt.figure(figsize=(15,10))

plt.pie(counts,labels=labels,autopct='%1.1f%%',shadow=True, colors=plt.cm.plasma(np.linspace(0,1,3)))
plt.show()

"""# Exploring Resume"""

df['Category'][0]

df['Resume'][0]

"""# Cleaning Data:                                      
1 URLs,                                                
2 hashtags,                                             
3 mentions,                                                     
4 special letters,                                             
5 punctuations:                                             
"""

import re
def cleanResume(txt):
    cleanText = re.sub('http\S+\s', ' ', txt)
    cleanText = re.sub('RT|cc', ' ', cleanText)
    cleanText = re.sub('#\S+\s', ' ', cleanText)
    cleanText = re.sub('@\S+', '  ', cleanText)
    cleanText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', cleanText)
    cleanText = re.sub(r'[^\x00-\x7f]', ' ', cleanText)
    cleanText = re.sub('\s+', ' ', cleanText)
    return cleanText

df['Resume'] = df['Resume'].apply(lambda x: cleanResume(x))

df['Resume'][0]

"""# words into categorical values"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(df['Category'])
df['Category'] = le.transform(df['Category'])

df.Category.unique()

# ['Data Science', 'HR', 'Advocate', 'Arts', 'Web Designing',
#        'Mechanical Engineer', 'Sales', 'Health and fitness',
#        'Civil Engineer', 'Java Developer', 'Business Analyst',
#        'SAP Developer', 'Automation Testing', 'Electrical Engineering',
#        'Operations Manager', 'Python Developer', 'DevOps Engineer',
#        'Network Security Engineer', 'PMO', 'Database', 'Hadoop',
#        'ETL Developer', 'DotNet Developer', 'Blockchain', 'Testing'],
#       dtype=object)

"""# Vactorization"""

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

tfidf.fit(df['Resume'])
requredText  = tfidf.transform(df['Resume'])

"""# Splitting"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(requredText, df['Category'], test_size=0.2, random_state=42)

X_train.shape

X_test.shape

"""# Now let’s train the model and print the classification report:"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score

clf = OneVsRestClassifier(KNeighborsClassifier())
clf.fit(X_train,y_train)
ypred = clf.predict(X_test)
print(accuracy_score(y_test,ypred))

ypred

"""# Prediction System"""

import pickle
pickle.dump(tfidf,open('tfidf.pkl','wb'))
pickle.dump(clf, open('clf.pkl', 'wb'))

myresume = """I am a data scientist specializing in machine
learning, deep learning, and computer vision. With
a strong background in mathematics, statistics,
and programming, I am passionate about
uncovering hidden patterns and insights in data.
I have extensive experience in developing
predictive models, implementing deep learning
algorithms, and designing computer vision
systems. My technical skills include proficiency in
Python, Sklearn, TensorFlow, and PyTorch.
What sets me apart is my ability to effectively
communicate complex concepts to diverse
audiences. I excel in translating technical insights
into actionable recommendations that drive
informed decision-making.
If you're looking for a dedicated and versatile data
scientist to collaborate on impactful projects, I am
eager to contribute my expertise. Let's harness the
power of data together to unlock new possibilities
and shape a better future.
Contact & Sources
Email: 611noorsaeed@gmail.com
Phone: 03442826192
Github: https://github.com/611noorsaeed
Linkdin: https://www.linkedin.com/in/noor-saeed654a23263/
Blogs: https://medium.com/@611noorsaeed
Youtube: Artificial Intelligence
ABOUT ME
WORK EXPERIENCE
SKILLES
NOOR SAEED
LANGUAGES
English
Urdu
Hindi
I am a versatile data scientist with expertise in a wide
range of projects, including machine learning,
recommendation systems, deep learning, and computer
vision. Throughout my career, I have successfully
developed and deployed various machine learning models
to solve complex problems and drive data-driven
decision-making
Machine Learnine
Deep Learning
Computer Vision
Recommendation Systems
Data Visualization
Programming Languages (Python, SQL)
Data Preprocessing and Feature Engineering
Model Evaluation and Deployment
Statistical Analysis
Communication and Collaboration
"""

myresume1 = """Sukkrishvar Vijay Santhana Krishnan
sukkrishvarvijay28@gmail.com | (475) 414-5562 | www.linkedin.com/in/sukkrishvarvijay | Website
SUMMARY
•	Dedicated Computer Science graduate student knowledgeable in Cybersecurity, Networks, Software Development. Possesses excellent client management skills and the ability to multitask effectively.
•	Familiar with Languages: Python, Java, C, C++, SQL, HTML, CSS, JavaScript.
•	Familiar with Tools: GitHub, Visual Studio Code, Burp Suite, Nessus, Nmap, MS Word, MS Excel, MS PowerPoint.
•	Knowledgeable in Operating Systems: Windows, LINUX.

EDUCATION
University of New Haven 									West Haven, CT
Master of Science, Computer Science | CGPA:4/4						May 2025

Vellore Institute of Technology								Chennai, India
Bachelor of Technology, Electronics and Communication | CGPA:8.57/10			May 2023

INTERNSHIP EXPERIENCE
SecureITLab 										Remote
Associate Consultant									Oct 2022 – Jun 2023
•	Developed and implemented data protection policies and procedures to ensure the confidentiality, integrity, and availability of sensitive information, specifically PII information.
•	Assisted in the development and implementation of data protection strategies for identified data elements.
•	Conducted regular audits of data protection processes and recommended improvements to ensure compliance with industry best practices.
•	Conducted business impact assessment exercises and developed Business Continuity Plans for various clients in the Philippines and  Kingdom of Bahrain.
•	Assisted in ISO Compliance project for various clients where the goal was to identify control weaknesses and provide ideas to strengthen the current control environment based on controls defined in ISO 27001, 27701, 22301.
Research Associate									Jul 2022 – Sep 2022
•	Researched different domains in cybersecurity and application of cybersecurity in various Industries, especially Banking, Financial Services and NIST Framework.
•	Performed External and Internal Vulnerability Assessment, External and Internal Penetration Testing, and Brand Assessment to test the integrity of company’s website and networks.
VOLUNTEER WORK
Vellore Institute of Technology, Rotary Club						Chennai, India
Club Service Member									Jul 2021 – May 2022
•	Effectively contributed to activities like event management, and resource management of all related events, especially the blood donation camp conducted in the academic year.
PROJECT
Blog Site – (Python, HTML, CSS, JavaScript)
•	Created a blog post site using HTML, CSS and JavaScript for frontend and Flask for backend to make the website dynamic.
Rain Alert via SMS – (Python)
•	Created a rain alert project in python which collects weather data from Open weather using API and sends SMS to your mobile using Twilio API by analyzing the weather data.
Stock Trading News alert – (Python)
•	Created a stock trading alert project in python which collects data from Alpha vantage API and sends alerts via SMS to your mobile using Twilio API by analyzing the stock price data.

"""

import pickle

# Load the trained classifier
clf = pickle.load(open('clf.pkl', 'rb'))

# Clean the input resume
cleaned_resume = cleanResume(myresume1)

# Transform the cleaned resume using the trained TfidfVectorizer
input_features = tfidf.transform([cleaned_resume])

# Make the prediction using the loaded classifier
prediction_id = clf.predict(input_features)[0]

# Map category ID to category name
category_mapping = {
    15: "Java Developer",
    23: "Testing",
    8: "DevOps Engineer",
    20: "Python Developer",
    24: "Web Designing",
    12: "HR",
    13: "Hadoop",
    3: "Blockchain",
    10: "ETL Developer",
    18: "Operations Manager",
    6: "Data Science",
    22: "Sales",
    16: "Mechanical Engineer",
    1: "Arts",
    7: "Database",
    11: "Electrical Engineering",
    14: "Health and fitness",
    19: "PMO",
    4: "Business Analyst",
    9: "DotNet Developer",
    2: "Automation Testing",
    17: "Network Security Engineer",
    21: "SAP Developer",
    5: "Civil Engineer",
    0: "Advocate",
}

category_name = category_mapping.get(prediction_id, "Unknown")

print("Predicted Category:", category_name)
print(prediction_id)

!pip install PyPDF2
!pip install docx2txt

# prompt: give a python code which will extract text from pdf file

# !pip install PyPDF2
import PyPDF2

# Open the PDF file in binary mode
with open('Resume.pdf', 'rb') as f:
  # Create a PDF reader object
  pdf_reader = PyPDF2.PdfReader(f)

  # Get the number of pages in the PDF file
  num_pages = len(pdf_reader.pages)

  # Extract text from each page
  text = []
  for page_num in range(num_pages):
    page = pdf_reader.pages[page_num]
    text.append(page.extract_text())

  # Combine the extracted text into a single string
  text = ''.join(text)

  # Print the extracted text
  print(text)

import PyPDF2

def pdftotext(file_name):
  with open('Resume.pdf', 'rb') as f:
    # Create a PDF reader object
    pdf_reader = PyPDF2.PdfReader(f)

    # Get the number of pages in the PDF file
    num_pages = len(pdf_reader.pages)

    # Extract text from each page
    text = []
    for page_num in range(num_pages):
      page = pdf_reader.pages[page_num]
      text.append(page.extract_text())

    # Combine the extracted text into a single string
    text = ''.join(text)

    return text

import docx2txt

# Path to the docx file
docx_file_path = 'Resume.docx'

# Extract text from the docx file
text1 = docx2txt.process(docx_file_path)

# Print the extracted text
print(text1)

import docx2txt

def docxtotext(file_name):
  docx_file_path = file_name

  # Extract text from the docx file
  text = docx2txt.process(docx_file_path)

  return text

def txttotext(file_name):
  with open(file_name, 'r') as file:
    text = file.read()
  return text

import re

def extract_education(text):
    # Define regex pattern for education
    education_pattern = r'((Bachelor\'s|Master\'s|Ph\.?D\.?)\s.*?(\d{4})\s*-\s*(Present|\d{4}))'
    # Find all matches
    education_matches = re.findall(education_pattern, text)
    # Return matched results
    return [match[0] for match in education_matches]

def extract_experience(text):
    # Define regex pattern for experience
    experience_pattern = r'((Internship|Work Experience|Experience)\s*:\s*(.*?)\s*-\s*(.*?)\s*:\s*(.*?)(?=Internship|Work Experience|Experience|$))'
    # Find all matches
    experience_matches = re.findall(experience_pattern, text, re.DOTALL)
    # Return matched results
    return experience_matches

def extract_projects(text):
    # Define regex pattern for projects
    projects_pattern = r'(Projects\s*:\s*(.*?)\s*-\s*(.*?)\s*:\s*(.*?)(?=Projects|$))'
    # Find all matches
    projects_matches = re.findall(projects_pattern, text, re.DOTALL)
    # Return matched results
    return projects_matches

# Sample text extracted from resume
resume_text = """
Education:
Bachelor's in Computer Science - 2016 - 2020

Experience:
Internship: Company A - June 2019 - August 2019:
- Worked on project X
- Collaborated with team members

Work Experience: Company B - January 2020 - Present:
- Developed software solutions
- Led a team of developers

Projects:
Projects: Project A - September 2018 - December 2018:
- Implemented feature Y
- Presented project at conference
"""

resume_text1 = text

# Extract education history
education_history = extract_education(resume_text1)
print("Education History:")
print(education_history)

# Extract work/internship experience
experience = extract_experience(resume_text1)
print("\nWork/Internship Experience:")
for exp in experience:
    print(exp)

# Extract projects
projects = extract_projects(resume_text1)
print("\nProjects:")
for project in projects:
    print(project)

import re

def extract_education(text):
    education_pattern = r'EDUCATION\s*(.*?)\s*University\s*of\s*New\s*Haven\s*(.*?)\s*\|\s*CGPA:\s*(\d+\.\d+)/(\d+\.\d+)\s*(.*?)\s*May\s*(\d{4})'
    education_matches = re.findall(education_pattern, text, re.DOTALL)
    return education_matches

def extract_experience(text):
    experience_pattern = r'INTERNSHIP\s*EXPERIENCE\s*(.*?)\s*(?:Associate\s*Consultant|Research\s*Associate)\s*(.*?)\s*(?:Oct\s*\d{4}\s*–\s*Jun\s*\d{4}|Jul\s*\d{4}\s*–\s*Sep\s*\d{4})'
    experience_matches = re.findall(experience_pattern, text, re.DOTALL)
    return experience_matches

def extract_projects(text):
    projects_pattern = r'PROJECT\s*(.*?)\s*(?:Blog\s*Site|Rain\s*Alert\s*via\s*SMS|Stock\s*Trading\s*News\s*alert)\s*–\s*\((.*?)\)'
    projects_matches = re.findall(projects_pattern, text, re.DOTALL)
    return projects_matches

resume_text = """
More Projects in GitHub Repositories: https://github.com/sukkrishvar -vijay Sukkrishvar Vijay Santhana Krishnan
sukkrishvarvijay28@gmail.com | (475) 414 -5562 | www.linkedin.com/in/sukkrishvarvijay | Website
SUMMARY
• Dedicated Computer Science graduate student knowledgeable in Cybersecurit y, Networks, Software Development.
Possesses excellent client management skills and the ability to multitask effectively.
• Familiar with Languages: Python, Java, C, C++ , SQL , HTML, CSS, JavaScript.
• Familiar with Tools: Git Hub, Visual Studio Code, Burp Suite, Nessus, Nmap , MS Word, MS Excel, MS PowerPoint .
• Knowledgeable in Operating Systems: Windows, LINUX.

EDUCATION
University of New Haven West Haven, CT
Master of Science , Computer Science | CGPA:4/4 May 2025

Vellore Institute of Technology Chennai, India
Bachelor of Technology, Electronics and Communication | CGPA:8.57/10 May 2023

INTERNSHIP EXPERIENCE
SecureITLab Remote
Associate Consultant Oct 2022 – Jun 2023
• Developed and implemented data protection policies and procedures to ensure the confidentiality, integrity, and
availability of sensitive information, specifically PII information.
• Assisted in the development and implementation of data protection strategies for identified data elements.
• Conducted regular audits of data protection processes and recommended improvements to ensure compliance with
industry best practices.
• Conducted business impact assessment exercises and developed Business Continuity Plans for various clients in the
Philippines and Kingdom of Bahrain.
• Assisted in ISO Compliance project for various clients where the goal was to identify control weaknesses and provide
ideas to strengthen the current control environment based on controls defined in ISO 27001 , 27701 , 22301.
Research Associate Jul 2022 – Sep 2022
• Researched different domains in cybersecurity and application of cybersecurity in various Industries, especially
Banking , Financial Services and NIST Framework .
• Performed External and Internal Vulnerability Assessment, External and Internal Penetration Testing , and Brand
Assessment to test the integrity of company’s website and networks .

VOLUNTEER WORK
Vellore Institute of Technology , Rotary Club Chennai, India
Club Service Member Jul 2021 – May 2022
• Effectively contributed to activities like event management, and resource management of all related events,
especially the blood donation camp conducted in the academic year.

PROJECT
Blog Site – (Python , HTML, CSS, JavaScript )
• Created a blog post site using HTML, CSS and JavaScript for frontend and Flask for backend to make the website
dynamic.
Rain Alert via SMS – (Python)
• Created a rain alert project in python which collects weather data from Open weather using API and sends SMS to
your mobile using Twilio API by analyzing the weather data.
Stock Trading News alert – (Python)
• Created a stock trading alert project in python which collects data from Alpha vantage API and sends alerts via SMS to
your mobile using Twilio API by analyzing the stock price data .
"""

education_history = extract_education(resume_text)
print("Education History:")
print(education_history)

experience = extract_experience(resume_text)
print("\nInternship Experience:")
for exp in experience:
    print(exp)

projects = extract_projects(resume_text)
print("\nProjects:")
for project in projects:
    print(project)

inputtext = input("Enter the File Name:")
inputtextsplit = inputtext.split(".")
# print(inputtext)
if(inputtextsplit[-1]=='docx'):
  resume = docxtotext(inputtext[-1])
if(inputtextsplit[-1]=='pdf'):
  resume = pdftotext(inputtext[-1])
if(inputtextsplit[-1]=='txt'):
  resume = txttotext(inputtext[-1])

print(resume)
